command: ['streamlit', 'run', 'app.py']

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "b04eb16e0536bd88"
  - name: "STREAMLIT_GATHER_USAGE_STATS"
    value: "false"

resources:
  - name: sql-warehouse
    sql_warehouse:
      id: b04eb16e0536bd88
      permission: CAN_USE

  - name: whisper-endpoint
    serving_endpoint:
      name: whisper_large_v3
      permission: CAN_QUERY

  - name: clip-endpoint
    serving_endpoint:
      name: clip_embedding_endpoint
      permission: CAN_QUERY

  - name: gemini-endpoint
    serving_endpoint:
      name: databricks-gemini-2-5-flash
      permission: CAN_QUERY

  - name: video-search-endpoint
    serving_endpoint:
      name: video-search-endpoint
      permission: CAN_QUERY
